let num1 = 31;
let num2 = 2;
let multiply = num1 * num2;
console.log(multiply);
let random = Math.floor(Math.random() * 10) + 1;
console.log(random);
let num3 = 28;
let num4 = 6;
let mod = num3 % num4;
console.log(mod);
let max = Math.max(17, 12, 3, 4, 20);
console.log (max);
